### ISSUE TITLE
Theme errors

### ISSUE THREAD

**Issue by Florin415** [ColorlibHQ/boxe#9]
When we try to customize the theme we get the following errors displayed :
https://prnt.sc/uz2la1
https://prnt.sc/uz2lgk
https://prnt.sc/uz2lkz

The errors are caused by the social profile show/hide toggle ; https://prnt.sc/uz2mtu

**Comment by mahendrapratap4022** [comment]
Hi it is fixed in https://github.com/ColorlibHQ/boxe/pull/12
Thanks for reporting it.
